from . import crm_lead
from . import res_config_settings
from . import res_partner
from . import whatsapp_helper
from . import product_trend_report
from . import stock_min_max_report
from . import goal_achievement_report
from . import customer_purchase_history_report
from . import whatsapp_sales_trend_report
